-- MakingDB: 테이블 생성 + RLS 정책
-- Supabase 대시보드 -> SQL Editor에서 이 파일 내용을 통째로 붙여넣고 Run 하세요.

create table public.recipes (
  id bigint generated by default as identity primary key,
  major_category text not null,
  sub_category text not null default '',
  name text not null unique,
  output_qty integer not null default 1,
  materials jsonb not null default '[]'::jsonb
);

create table public.scrolls (
  id bigint generated by default as identity primary key,
  scroll_type text not null,
  town text not null default '',
  target_name text not null,
  qty_per_scroll integer not null default 1,
  unique (scroll_type, target_name)
);

create table public.materials (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Row Level Security 활성화
alter table public.recipes enable row level security;
alter table public.scrolls enable row level security;
alter table public.materials enable row level security;

-- 누구나 조회 가능 (조회 전용 웹뷰어가 이 정책으로 데이터를 읽습니다)
create policy "public read recipes" on public.recipes for select using (true);
create policy "public read scrolls" on public.scrolls for select using (true);
create policy "public read materials" on public.materials for select using (true);

-- 로그인한 사용자만 추가/수정/삭제 가능
create policy "auth insert recipes" on public.recipes for insert to authenticated with check (true);
create policy "auth update recipes" on public.recipes for update to authenticated using (true) with check (true);
create policy "auth delete recipes" on public.recipes for delete to authenticated using (true);

create policy "auth insert scrolls" on public.scrolls for insert to authenticated with check (true);
create policy "auth update scrolls" on public.scrolls for update to authenticated using (true) with check (true);
create policy "auth delete scrolls" on public.scrolls for delete to authenticated using (true);

create policy "auth insert materials" on public.materials for insert to authenticated with check (true);
create policy "auth delete materials" on public.materials for delete to authenticated using (true);
